/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'TestSerialMsg'
 * message type.
 */

public class TestSerialMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 5;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 137;

    /** Create a new TestSerialMsg of size 5. */
    public TestSerialMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new TestSerialMsg of the given data_length. */
    public TestSerialMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TestSerialMsg with the given data_length
     * and base offset.
     */
    public TestSerialMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TestSerialMsg using the given byte array
     * as backing store.
     */
    public TestSerialMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TestSerialMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public TestSerialMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TestSerialMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public TestSerialMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TestSerialMsg embedded in the given message
     * at the given base offset.
     */
    public TestSerialMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TestSerialMsg embedded in the given message
     * at the given base offset and length.
     */
    public TestSerialMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <TestSerialMsg> \n";
      try {
        s += "  [node_id=0x"+Long.toHexString(get_node_id())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [trash_level=0x"+Long.toHexString(get_trash_level())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [status=0x"+Long.toHexString(get_status())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [outside_trash=0x"+Long.toHexString(get_outside_trash())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: node_id
    //   Field type: int, unsigned
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'node_id' is signed (false).
     */
    public static boolean isSigned_node_id() {
        return false;
    }

    /**
     * Return whether the field 'node_id' is an array (false).
     */
    public static boolean isArray_node_id() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'node_id'
     */
    public static int offset_node_id() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'node_id'
     */
    public static int offsetBits_node_id() {
        return 0;
    }

    /**
     * Return the value (as a int) of the field 'node_id'
     */
    public int get_node_id() {
        return (int)getUIntBEElement(offsetBits_node_id(), 16);
    }

    /**
     * Set the value of the field 'node_id'
     */
    public void set_node_id(int value) {
        setUIntBEElement(offsetBits_node_id(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'node_id'
     */
    public static int size_node_id() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'node_id'
     */
    public static int sizeBits_node_id() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: trash_level
    //   Field type: short, unsigned
    //   Offset (bits): 16
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'trash_level' is signed (false).
     */
    public static boolean isSigned_trash_level() {
        return false;
    }

    /**
     * Return whether the field 'trash_level' is an array (false).
     */
    public static boolean isArray_trash_level() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'trash_level'
     */
    public static int offset_trash_level() {
        return (16 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'trash_level'
     */
    public static int offsetBits_trash_level() {
        return 16;
    }

    /**
     * Return the value (as a short) of the field 'trash_level'
     */
    public short get_trash_level() {
        return (short)getUIntBEElement(offsetBits_trash_level(), 8);
    }

    /**
     * Set the value of the field 'trash_level'
     */
    public void set_trash_level(short value) {
        setUIntBEElement(offsetBits_trash_level(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'trash_level'
     */
    public static int size_trash_level() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'trash_level'
     */
    public static int sizeBits_trash_level() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: status
    //   Field type: short, unsigned
    //   Offset (bits): 24
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'status' is signed (false).
     */
    public static boolean isSigned_status() {
        return false;
    }

    /**
     * Return whether the field 'status' is an array (false).
     */
    public static boolean isArray_status() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'status'
     */
    public static int offset_status() {
        return (24 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'status'
     */
    public static int offsetBits_status() {
        return 24;
    }

    /**
     * Return the value (as a short) of the field 'status'
     */
    public short get_status() {
        return (short)getUIntBEElement(offsetBits_status(), 8);
    }

    /**
     * Set the value of the field 'status'
     */
    public void set_status(short value) {
        setUIntBEElement(offsetBits_status(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'status'
     */
    public static int size_status() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'status'
     */
    public static int sizeBits_status() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: outside_trash
    //   Field type: short, unsigned
    //   Offset (bits): 32
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'outside_trash' is signed (false).
     */
    public static boolean isSigned_outside_trash() {
        return false;
    }

    /**
     * Return whether the field 'outside_trash' is an array (false).
     */
    public static boolean isArray_outside_trash() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'outside_trash'
     */
    public static int offset_outside_trash() {
        return (32 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'outside_trash'
     */
    public static int offsetBits_outside_trash() {
        return 32;
    }

    /**
     * Return the value (as a short) of the field 'outside_trash'
     */
    public short get_outside_trash() {
        return (short)getUIntBEElement(offsetBits_outside_trash(), 8);
    }

    /**
     * Set the value of the field 'outside_trash'
     */
    public void set_outside_trash(short value) {
        setUIntBEElement(offsetBits_outside_trash(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'outside_trash'
     */
    public static int size_outside_trash() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'outside_trash'
     */
    public static int sizeBits_outside_trash() {
        return 8;
    }

}
